config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'welcome#home'

    get "user/uprofile",                                                    as:"uprofile"
    get "user/muserr",                                                      as:"all_users"
    post "user/muserr",                                                     as:"user_sort"
    delete "user/:id/del",                          to:"user#muserdp",      as:"user_delete"
    get "user/uform",                                                       as:"form"
    patch "user/uformp",                                                    as:"form_post"
    
    get "welcome/mhomer",                                                   as:"home"
    get "welcome/mnewsc",                                                   as:"new_news"
    post "welcome/mnewscp",                                                 as:"news_post"
    get "news/:id/up",                              to:"welcome#mnewsu",    as:"news"
    patch "news/:id",                               to:"welcome#mnewsup",   as:"news_update"
    delete "news/:id/del",                          to:"welcome#mnewsdp",   as:"news_delete"

    get "welcome/about",                                                    as:"about"
    get "welcome/htuse",                                                    as:"htuse"
    get "welcome/terms",                                                    as:"terms"
    get "welcome/maboutu",                                                  as:"about_change"
    get "welcome/mhtuseu",                                                  as:"htuse_change"
    get "welcome/mtermsu",                                                  as:"terms_change"
    patch "welcome/maboutup",                                               as:"about_update"
    patch "welcome/mhtuseup",                                               as:"htuse_update"
    patch "welcome/mtermsup",                                               as:"terms_update"

    get "game/ugame",                                                       as:"games"
    get "game/uview/:id",                           to:"game#ugamen",       as:"game_uview"
    get "game/mgamer",                                                      as:"all_games"
    get "game/mgamec",                                                      as:"new_game"
    post "game/mgamecp",                                                    as:"game_post"
    get "game/:id/up",                              to:"game#mgameu",       as:"game"
    patch "game/:id",                                to:"game#mgameup",      as:"game_update"
    delete "game/:id/del",                          to:"game#mgamedp",      as:"game_delete"

    get "logging/mnew",                                                     as:"new_member"
    get "logging/unew",                                                     as:"new_user"
    post "logging/newp",                                                    as:"newp"
    post "logging/otpp",                                                    as:"otpp"
    get "logging/mlogin",                                                   as:"member_login"
    get "logging/ulogin",                                                   as:"user_login"
    post "logging/loginp",                                                  as:"login_post"
    get "logging/logout",                                                   as:"logout"
    get "logging/forgot",                                                   as:"forgot"
    post "logging/forgotp",                                                 as:"forgotp"
    post "logging/resetp",                                                  as:"resetp"
    get "reset_otp",                             to: "logging#reset_otp",  as: "reset_otp"

    get "course/ucourse",                                                   as:"courses"
    get "course/mcourser",                                                  as:"all_courses"
    get "course/mcoursec",                                                  as:"new_course"
    post "course/mcoursecp",                                                as:"course_post"
    get "course/:id/up",                            to:"course#mcourseu",   as:"course"
    patch "course/:id",                             to:"course#mcourseup",  as:"course_update"
    delete "course/:id/del",                        to:"course#mcoursedp",  as:"course_delete"
    get "course/:cname/uview",                      to:"course#ucourse1",   as:"course_uview"
    get "course/:cname/reg",                        to:"course#ureg",       as:"course_reg"
    # post "course/:name/reg",                      to:"course#uformp"

    get "feedback/ufeedback",                                               as:"feedback"
    post "feedback/ufeedbackp",                                             as:"feedback_post"
    get "feedback/mfeedbackr",                                              as:"all_feedbacks"

    get "shlok/ushlok",                                                     as:"shloks"
    get "shlok/mshlokr",                                                    as:"all_shloks"
    get "shlok/mshlokc",                                                    as:"new_shlok"
    post "shlok/mshlokcp",                                                  as:"shlok_post"
    get "shlok/:id/up",                             to:"shlok#mshloku",     as:"shlok"
    patch "shlok/:id",                              to:"shlok#mshlokup",    as:"shlok_update"
    delete "shlok/:id/del",                         to:"shlok#mshlokdp",    as:"shlok_delete"

    get "event/uevent",                                                     as:"events"
    get "event/meventr",                                                    as:"all_events"
    get "event/meventc",                                                    as:"new_event"
    post "event/meventcp",                                                  as:"event_post"
    get "event/:id/up",                             to:"event#meventu",     as:"event"
    patch "event/:id",                              to:"event#meventup",    as:"event_update"
    delete "event/:id/del",                         to:"event#meventdp",    as:"event_delete"
    get 'event/uview/:id', to: 'event#ueventn', as: 'event_uview'


    get "resource/uresource",                                                     as:"resources"
    get "resource/mresourcer",                                                    as:"all_resources"
    get "resource/mresourcec",                                                    as:"new_resource"
    post "resource/mresourcecp",                                                  as:"resource_post"
    get "resource/:id/up",                             to:"resource#mresourceu",     as:"resource"
    patch "resource/:id",                              to:"resource#mresourceup",    as:"resource_update"
    delete "resource/:id/del",                         to:"resource#mresourcedp",    as:"resource_delete"

    get "exam/:cname/:ename/uview",                 to:"exam#uexam1",       as:"exam_uview"
    post "exam/:cname/:ename/upost",                to:"exam#uexamp",       as:"exam_upost"
    get "exam/:cname/new",                          to:"exam#mexamc",       as:"exam_new"
    post "exam/:cname/create",                      to:"exam#mexamcp",      as:"exam_create"
    get "exam/:cname/:ename/ch",                    to:"exam#mexamu",       as:"exam_change"
    patch "exam/:cname/:ename/up",                  to:"exam#mexamup",      as:"exam_update"
    delete "exam/:cname/:ename/del",                to:"exam#mexamdp",      as:"exam_delete"
    get "exam/:cname/:ename/r",                     to:"exam#mquescr",      as:"ques_read"
    post "exam/:cname/:ename/c",                    to:"exam#mquescr",      as:"ques_create"
    get "exam/:cname/:ename/:qno/ch",               to:"exam#mquesu",       as:"ques_change"
    patch "exam/:cname/:ename/:qno/up",             to:"exam#mquesup",      as:"ques_update"
    delete "exam/:cname/:ename/:qno/del",           to:"exam#mquesdp",      as:"ques_delete"

    get "member/uteam",                                                     as:"members"
    get "member/mmemberr",                                                  as:"all_members"
    get "member/:id/up",                            to:"member#mmemberu",   as:"member"
    patch "member/:id",                             to:"member#mmemberup",  as:"member_update"
    delete "member/:id/del",                        to:"member#mmemberdp",  as:"member_delete"
    get "member/memarea",                                                   as:"member_area"
    get "member/mprofile",                                                  as:"mprofile"
    get "member/mchanger",                                                  as:"all_changes"
    get "member/msql",                                                      as:"msql"
    post "member/msql",                                                     as:"exec_sql"

    get "exam/:cname/:ename/re_marks",              to:"exam#re_marks",     as:"re_marks"
    get "exam/:cname/mp_marks",                     to:"exam#mp_marks",     as:"mp_marks"

    get "library/ulibrary",                                                     as:"librarys"
    get "library/mlibraryr",                                                    as:"all_librarys"
    get "library/mlibraryc",                                                    as:"new_library"
    post "library/mlibrarycp",                                                  as:"library_post"
    get "library/:id/up",                             to:"library#mlibraryu",     as:"library"
    patch "library/:id",                              to:"library#mlibraryup",    as:"library_update"

app/models/game.rb
class Game < ApplicationRecord

    has_one_attached :image
    
    validates :name, presence: true
    validates :info, presence: true
    
end

app/controllers/game_controller.rb
class GameController < ApplicationController
    def ugame
        @games = Game.all
        render "ugame"
    end

    def ugamen
        @game = Game.find_by(id: params[:id])
        if @game
            render "ugamen"
        else
            flash[:alert] = "क्रीडा न प्राप्ता!"
            redirect_to games_path
        end
    end

    def mgamer
        if session[:member]
            @games = Game.all
            render "mgamer"
        else
            redirect_to root_url
        end
    end

    def mgamec
        if session[:member]
            render "mgamec"
        else
            redirect_to root_url
        end
    end

    def mgameu
        if session[:member]
            @game = Game.find_by(id: params[:id])
            render "mgameu"
        else
            redirect_to root_url
        end
    end

    def mgamecp
        game = Game.new(:name => params[:name], :info => params[:info])
        if params[:image].present?
            game.image.attach(params[:image])
        end
        game.save
        change = Change.new(:time => Time.now, :email => session[:email], :table => "games", :cord => "create")
        change.save
        flash[:notice] = "नूतनः क्रीडा योजितः जातः!"
        redirect_to all_games_path
    end
    
    def mgamedp
        game = Game.find(params[:id])
        game.destroy
        change = Change.new(:time => Time.now, :email => session[:email], :table => "games", :cord => "delete")
        change.save
        flash[:notice] = "क्रीडा विनष्टः जातः!"
        redirect_to all_games_path
    end

    def mgameup
        game = Game.find(params[:id])
        
        # Update basic attributes
        game.update(name: params[:game][:name], info: params[:game][:info])
        
        # Attach new image if provided
        if params[:game][:image].present?
            game.image.attach(params[:game][:image])
        end
        
        # Log the change
        change = Change.new(:time => Time.now, :email => session[:email], :table => "games", :cord => "update")
        change.save
        
        flash[:notice] = "क्रीडा परिवर्तितः जातः!"
        redirect_to all_games_path
    end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/mgamec.html.erb
<div class="form-page">
  <div class="form-container">
    <div class="form-header">
      <div class="greeting">नमस्ते 🙏</div>
      <h1>नूतनं क्रीडां योजयतु</h1>
      <p class="form-subtitle">नवीनं क्रीडां सृजयतु</p>
    </div>

    <%= form_with url: game_post_path, multipart: true, local: true, class: "modern-form" do |f| %>
      <div class="form-group">
        <%= label_tag "शीर्षकं", nil, class: "form-label" %>
        <%= text_field_tag :name, nil, required: true, class: "form-input", placeholder: "क्रीडायाः नाम..." %>
      </div>

      <div class="form-group">
        <%= label_tag "क्रीडा", nil, class: "form-label" %>
        <%= text_area_tag :info, nil, required: true, class: "form-textarea", placeholder: "क्रीडायाः विवरणं लिखतु...", rows: 6 %>
      </div>

      <div class="form-group">
        <%= label_tag "चित्रम्", nil, class: "form-label" %>
        <div class="file-input-wrapper">
          <%= file_field_tag :image, class: "file-input", id: "game-image-input", accept: "image/*" %>
          <label for="game-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span id="image-file-name">चित्रं चिनोतु (वैकल्पिकम्)</span>
          </label>
        </div>
        <div id="image-preview" class="file-preview"></div>
      </div>

      <div class="form-actions">
        <%= submit_tag "अग्रेस्थापनं करोतु", class: "btn btn-primary" %>
        <%= link_to "प्रतिगच्छतु", all_games_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const fileInput = document.getElementById('game-image-input');
  const fileNameDisplay = document.getElementById('image-file-name');
  const imagePreview = document.getElementById('image-preview');
  
  fileInput.addEventListener('change', function() {
    if (this.files && this.files.length > 0) {
      const fileName = this.files[0].name;
      fileNameDisplay.textContent = fileName;
      
      // Show image preview
      const reader = new FileReader();
      reader.onload = function(e) {
        imagePreview.innerHTML = `
          <img src="${e.target.result}" alt="Preview" style="max-width: 100%; height: auto; border-radius: 8px; margin-top: 1rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        `;
      };
      reader.readAsDataURL(fileInput.files[0]);
    } else {
      fileNameDisplay.textContent = 'चित्रं चिनोतु (वैकल्पिकम्)';
      imagePreview.innerHTML = '';
    }
  });
});
</script>

app/views/game/mgamer.html.erb
<div class="admin-games-page">
  <div class="admin-header">
    <h1>क्रीडा-प्रबन्धनम्</h1>
    <p class="admin-subtitle">सर्वाः क्रीडाः सम्पादयतु</p>
    <%= link_to new_game_path, class: "btn btn-create" do %>
      <span class="btn-icon">➕</span>
      नूतनं क्रीडां योजयतु
    <% end %>
  </div>

  <div class="admin-games-container">
    <% @games.each do |game| %>
      <div class="admin-game-card">
        <div class="admin-game-header">
          <div class="game-badge">🎮 क्रीडा</div>
        </div>
        
        <div class="admin-game-content">
          <h2 class="admin-game-title"><%= game.name %></h2>
          <div class="admin-game-info">
            <%= truncate(game.info.html_safe, length: 150) %>
          </div>
          
          <div class="admin-game-actions">
            <%= link_to game_path(game.id), class: "btn btn-edit" do %>
              <span class="btn-icon">✏️</span>
              परिवर्तयतु
            <% end %>
            <%= button_to game_delete_path(game.id),
                method: :delete,
                data: { confirm: "किं भवान् निश्चितः अस्ति यत् एतं क्रीडां विनाशयितुम् इच्छति?" },
                class: "btn btn-delete" do %>
              <span class="btn-icon">🗑️</span>
              विनश्यतु
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/game/mgameu.html.erb
<div class="form-page">
  <div class="form-container">
    <div class="form-header">
      <div class="greeting">नमस्ते 🙏</div>
      <h1>क्रीडां परिवर्तयतु</h1>
      <p class="form-subtitle">क्रीडायाः विवरणं नवीकरोतु</p>
    </div>

    <%= form_for @game, url: game_update_path, html: { multipart: true, class: "modern-form" } do |f| %>
      <div class="form-group">
        <%= f.label :name, "शीर्षकं", class: "form-label" %>
        <%= f.text_field :name, required: true, class: "form-input", placeholder: "क्रीडायाः नाम..." %>
      </div>

      <div class="form-group">
        <%= f.label :info, "क्रीडा", class: "form-label" %>
        <%= f.text_area :info, required: true, class: "form-textarea", placeholder: "क्रीडायाः विवरणं लिखतु...", rows: 6 %>
      </div>

      <div class="form-group">
        <%= f.label :image, "चित्रम्", class: "form-label" %>
        
        <% if @game.image.attached? %>
          <div class="current-image">
            <%= image_tag @game.image, alt: @game.name, style: "max-width: 100%; height: auto; border-radius: 8px; margin-bottom: 1rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" %>
            <p style="color: #5a6c7d; font-size: 0.9rem; margin-top: 0.5rem;">वर्तमानं चित्रम्</p>
          </div>
        <% end %>

        <div class="file-input-wrapper">
          <%= f.file_field :image, class: "file-input", id: "game-image-input", accept: "image/*" %>
          <label for="game-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span id="image-file-name">नवीनं चित्रं चिनोतु (वैकल्पिकम्)</span>
          </label>
        </div>
        <div id="image-preview" class="file-preview"></div>
      </div>

      <div class="form-actions">
        <%= f.submit "नवीकरोतु", class: "btn btn-primary" %>
        <%= link_to "प्रतिगच्छतु", all_games_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const fileInput = document.getElementById('game-image-input');
  const fileNameDisplay = document.getElementById('image-file-name');
  const imagePreview = document.getElementById('image-preview');
  
  fileInput.addEventListener('change', function() {
    if (this.files && this.files.length > 0) {
      const fileName = this.files[0].name;
      fileNameDisplay.textContent = fileName;
      
      // Show image preview
      const reader = new FileReader();
      reader.onload = function(e) {
        imagePreview.innerHTML = `
          <img src="${e.target.result}" alt="Preview" style="max-width: 100%; height: auto; border-radius: 8px; margin-top: 1rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        `;
      };
      reader.readAsDataURL(fileInput.files[0]);
    } else {
      fileNameDisplay.textContent = 'नवीनं चित्रं चिनोतु (वैकल्पिकम्)';
      imagePreview.innerHTML = '';
    }
  });
});
</script>

app/views/game/ugame.html.erb
<div class="games-page">
  <div class="page-header">
    <h1>क्रीडाः</h1>
    <p class="subtitle">सर्वाः क्रीडाः अन्वेषयतु</p>
  </div>

  <div class="games-container">
    <% @games.each do |game| %>
      <div class="game-card">
        <% if game.image.attached? %>
          <div class="game-image">
            <%= image_tag game.image, alt: game.name %>
          </div>
        <% else %>
          <div class="game-header">
            <div class="game-badge">🎮 क्रीडा</div>
          </div>
        <% end %>
        
        <div class="game-content">
          <h2 class="game-title"><%= game.name %></h2>
          <div class="game-info">
            <%= truncate(strip_tags(game.info), length: 200, separator: ' ') %>
          </div>
          
          <div class="game-actions">
            <%= link_to game_uview_path(game.id), class: "anone" do %>
              <span>अधिकं पठतु</span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <% if @games.empty? %>
    <div style="text-align: center; padding: 3rem; color: #5a6c7d;">
      <p style="font-size: 1.2rem;">अधुना क्रीडाः न सन्ति</p>
      <p>शीघ्रमेव नूतनाः क्रीडाः आगमिष्यन्ति!</p>
    </div>
  <% else %>
    <div style="text-align: center; padding: 2rem; color: #5a6c7d; font-size: 1.1rem;">
      अधिकाः क्रीडाः शीघ्रमेव आगमिष्यन्ति!
    </div>
  <% end %>
</div>

app/views/game/ugamen.html.erb
<div class="game-detail-page">
  <div class="game-detail-container">
    <div class="game-detail-header">
      <h1 class="game-detail-title"><%= @game.name %></h1>
    </div>
    
    <% if @game.image.attached? %>
      <div class="game-detail-image">
        <%= image_tag @game.image, alt: @game.name %>
      </div>
    <% end %>
    
    <div class="game-detail-content">
      <%= @game.info.html_safe %>
    </div>
    
    <div class="back-button">
      <%= link_to games_path, class: "btn btn-secondary" do %>
        ← प्रतिगच्छतु
      <% end %>
    </div>
  </div>
</div>