config/routes.rb
    get "user/uform",                                                       as:"form"
    patch "user/uformp",                                                    as:"form_post"
    
    get "welcome/mhomer",                                                   as:"home"
    get "welcome/mnewsc",                                                   as:"new_news"
    post "welcome/mnewscp",                                                 as:"news_post"
    get "news/:id/up",                              to:"welcome#mnewsu",    as:"news"
    patch "news/:id",                               to:"welcome#mnewsup",   as:"news_update"
    delete "news/:id/del",                          to:"welcome#mnewsdp",   as:"news_delete"

    get "welcome/about",                                                    as:"about"
    get "welcome/htuse",                                                    as:"htuse"
    get "welcome/terms",                                                    as:"terms"
    get "welcome/maboutu",                                                  as:"about_change"
    get "welcome/mhtuseu",                                                  as:"htuse_change"
    get "welcome/mtermsu",                                                  as:"terms_change"
    patch "welcome/maboutup",                                               as:"about_update"
    patch "welcome/mhtuseup",                                               as:"htuse_update"
    patch "welcome/mtermsup",                                               as:"terms_update"

    get "game/ugame",                                                       as:"games"
    get "game/uview/:id",                           to:"game#ugamen",       as:"game_uview"
    get "game/mgamer",                                                      as:"all_games"
    get "game/mgamec",                                                      as:"new_game"
    post "game/mgamecp",                                                    as:"game_post"
    get "game/:id/up",                              to:"game#mgameu",       as:"game"
    patch "game/:id",                                to:"game#mgameup",      as:"game_update"
    delete "game/:id/del",                          to:"game#mgamedp",      as:"game_delete"

    get "logging/mnew",                                                     as:"new_member"
    get "logging/unew",                                                     as:"new_user"
    post "logging/newp",                                                    as:"newp"
    post "logging/otpp",                                                    as:"otpp"
    get "logging/mlogin",                                                   as:"member_login"
    get "logging/ulogin",                                                   as:"user_login"
    post "logging/loginp",                                                  as:"login_post"
    get "logging/logout",                                                   as:"logout"
    get "logging/forgot",                                                   as:"forgot"
    post "logging/forgotp",                                                 as:"forgotp"
    post "logging/resetp",                                                  as:"resetp"
    get "reset_otp",                             to: "logging#reset_otp",  as: "reset_otp"

    get "course/ucourse",                                                   as:"courses"
    get "course/mcourser",                                                  as:"all_courses"
    get "course/mcoursec",                                                  as:"new_course"
    post "course/mcoursecp",                                                as:"course_post"
    get "course/:id/up",                            to:"course#mcourseu",   as:"course"
    patch "course/:id",                             to:"course#mcourseup",  as:"course_update"
    delete "course/:id/del",                        to:"course#mcoursedp",  as:"course_delete"
    get "course/:cname/uview",                      to:"course#ucourse1",   as:"course_uview"
    get "course/:cname/reg",                        to:"course#ureg",       as:"course_reg"
    # post "course/:name/reg",                      to:"course#uformp"

    get "feedback/ufeedback",                                               as:"feedback"
    post "feedback/ufeedbackp",                                             as:"feedback_post"
    get "feedback/mfeedbackr",                                              as:"all_feedbacks"

    get "shlok/ushlok",                                                     as:"shloks"
    get "shlok/mshlokr",                                                    as:"all_shloks"
    get "shlok/mshlokc",                                                    as:"new_shlok"
    post "shlok/mshlokcp",                                                  as:"shlok_post"
    get "shlok/:id/up",                             to:"shlok#mshloku",     as:"shlok"
    patch "shlok/:id",                              to:"shlok#mshlokup",    as:"shlok_update"
    delete "shlok/:id/del",                         to:"shlok#mshlokdp",    as:"shlok_delete"

    get "event/uevent",                                                     as:"events"
    get "event/meventr",                                                    as:"all_events"
    get "event/meventc",                                                    as:"new_event"
    post "event/meventcp",                                                  as:"event_post"
    get "event/:id/up",                             to:"event#meventu",     as:"event"
    patch "event/:id",                              to:"event#meventup",    as:"event_update"
    delete "event/:id/del",                         to:"event#meventdp",    as:"event_delete"
    get 'event/uview/:id', to: 'event#ueventn', as: 'event_uview'


    get "resource/uresource",                                                     as:"resources"
    get "resource/mresourcer",                                                    as:"all_resources"
    get "resource/mresourcec",                                                    as:"new_resource"
    post "resource/mresourcecp",                                                  as:"resource_post"
    get "resource/:id/up",                             to:"resource#mresourceu",     as:"resource"
    patch "resource/:id",                              to:"resource#mresourceup",    as:"resource_update"
    delete "resource/:id/del",                         to:"resource#mresourcedp",    as:"resource_delete"

    get "exam/:cname/:ename/uview",                 to:"exam#uexam1",       as:"exam_uview"
    post "exam/:cname/:ename/upost",                to:"exam#uexamp",       as:"exam_upost"
    get "exam/:cname/new",                          to:"exam#mexamc",       as:"exam_new"
    post "exam/:cname/create",                      to:"exam#mexamcp",      as:"exam_create"
    get "exam/:cname/:ename/ch",                    to:"exam#mexamu",       as:"exam_change"
    patch "exam/:cname/:ename/up",                  to:"exam#mexamup",      as:"exam_update"
    delete "exam/:cname/:ename/del",                to:"exam#mexamdp",      as:"exam_delete"
    get "exam/:cname/:ename/r",                     to:"exam#mquescr",      as:"ques_read"
    post "exam/:cname/:ename/c",                    to:"exam#mquescr",      as:"ques_create"
    get "exam/:cname/:ename/:qno/ch",               to:"exam#mquesu",       as:"ques_change"
    patch "exam/:cname/:ename/:qno/up",             to:"exam#mquesup",      as:"ques_update"
    delete "exam/:cname/:ename/:qno/del",           to:"exam#mquesdp",      as:"ques_delete"

    get "member/uteam",                                                     as:"members"
    get "member/mmemberr",                                                  as:"all_members"
    get "member/:id/up",                            to:"member#mmemberu",   as:"member"
    patch "member/:id",                             to:"member#mmemberup",  as:"member_update"
    delete "member/:id/del",                        to:"member#mmemberdp",  as:"member_delete"
    get "member/memarea",                                                   as:"member_area"
    get "member/mprofile",                                                  as:"mprofile"
    get "member/mchanger",                                                  as:"all_changes"
    get "member/msql",                                                      as:"msql"
    post "member/msql",                                                     as:"exec_sql"

    get "exam/:cname/:ename/re_marks",              to:"exam#re_marks",     as:"re_marks"
    get "exam/:cname/mp_marks",                     to:"exam#mp_marks",     as:"mp_marks"

    get "library/ulibrary",                                                     as:"librarys"
    get "library/mlibraryr",                                                    as:"all_librarys"
    get "library/mlibraryc",                                                    as:"new_library"
    post "library/mlibrarycp",                                                  as:"library_post"
    get "library/:id/up",                             to:"library#mlibraryu",     as:"library"
    patch "library/:id",                              to:"library#mlibraryup",    as:"library_update"
    delete "library/:id/del",                         to:"library#mlibrarydp",    as:"library_delete"
    
    get "team/uteam",                                                       as:"teams"
    get "team/mteamr",                                                      as:"all_teams"
    get "team/mteamc",                                                      as:"new_team"
    post "team/mteamcp",                                                    as:"team_post"
    get "team/:id/up",                              to:"team#mteamu",       as:"team"

app/models/course.rb
class Course < ApplicationRecord
    has_one_attached :image
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
    def ucourse
        @courses = Course.all.order(id: :desc)
        render "ucourse"
    end

    def mcourser
        if session[:member]
            @courses = Course.all.order(id: :desc)
            @exams = Exam.all
            render "mcourser"
        else
            redirect_to root_url
        end
    end

    def mcoursec
        if session[:member]
            render "mcoursec"
        else
            redirect_to root_url
        end
    end

    def mcoursecp
        course = Course.new(:name => params[:name], :cname => params[:cname], :regon =>params[:regon], :more => params[:more], :yt => params[:yt],
                            :description => params[:description], :image => params[:image])
        course.save
        change = Change.new(:time => Time.now, :email => session[:email], :table => "courses", :cord => "create")
        change.save

        ActiveRecord::Base.connection.execute("create table " + params[:cname] +
            "(id serial primary key, pid int, regid varchar(10), email varchar(50),
            constraint fk_user_id foreign key(pid) references users(id));")

        flash[:notice] = "New course created!"
        redirect_to all_courses_path
    end

    def mcourseu
        if session[:member]
            @course = Course.find(params[:id])
            render "mcourseu"
        else
            redirect_to root_url
        end
    end

    def mcourseup
        course = Course.find(params[:id])
        pp = params[:course]
        if !(course.cname == pp[:cname])
            ActiveRecord::Base.connection.execute("alter table " + course.cname + " rename to " + pp[:cname] + ";")
        end
        course.update(:name => pp[:name], :cname => pp[:cname], :regon =>pp[:regon], :description => pp[:description], :more => pp[:more], :yt => pp[:yt])
        if pp[:image].present?
            course.image.purge
            course.image.attach(pp[:image])
        end
        change = Change.new(:time => Time.now, :email => session[:email], :table => "courses", :cord => "update")
        change.save
        flash[:notice] = "CourseH परिवर्तितः जातः!"
        redirect_to all_courses_path
    end

    def mcoursedp
        if session[:member]
            course = Course.find(params[:id])
            course_parts = ActiveRecord::Base.connection.exec_query("select pid from " + course.cname + ";")
            for i in course_parts.rows
                user = User.find(i[0])
                user_courses = user.courses.split(", ") - [course.cname]
                user.update(:courses => user_courses.join(", "))
            end
            ActiveRecord::Base.connection.execute("drop table if exists " + course.cname + ";")
            course.destroy
            change = Change.new(:time => Time.now, :email => session[:email], :table => "courses", :cord => "delete")
            change.save
            redirect_to all_courses_path
        else
            redirect_to root_url
        end
    end

    def ucourse1
        email = session[:email]
        table = params[:cname]
        @course = Course.find_by(cname: table)
        @exams = Exam.all
        @user_regd = 0
        if session[:user]
            # @user = User.find_by(email: email)
            @user_regd = ActiveRecord::Base.connection.execute("select count(*) from " + table + " where email='" + email + "';")[0]["count"] # one way
        end
        render "ucourse1"
    end

    def ureg
        if session[:user]
            email = session[:email]
            user = User.find_by(email: email)
            if user.profile
                table = params[:cname]
                # if user.courses.include? table # another way of saying the same thing
                user_regd = ActiveRecord::Base.connection.execute("select count(*) from " + table + " where email='" + email + "';")[0]["count"]
                if user_regd > 0
                    redirect_to course_uview_path(table)
                else
                    user_regid = ""
                    if user.regid.nil?
                        var = Bgvar.first
                        user_regid = var.regid[0..2] + (var.regid[2..-1].to_i + 1).to_s.rjust(4, "0")
                        var.update(:regid => user_regid)
                        user.update(:regid => user_regid)
                    else
                        user_regid = user.regid
                    end
                    pid = user.id
                    query = "insert into " + table + "(pid, regid, email) values(" + pid.to_s + ", '" + user_regid + "', '" + email + "');"
                    ActiveRecord::Base.connection.execute(query)
                    if user.courses.nil?
                        user.courses = table
                    else
                        user.courses += ", " + table
                    end
                    user.update(:courses => user.courses)
                    course = Course.find_by(cname: table).name
                    CourseMailer.with(course: course, user_email: email).ureg_mail.deliver_later
                    flash[:notice] = "You have successfully registered for the course!"
                    redirect_to course_uview_path(table)
                end
            else
                flash[:notice] = "Please update your profile to register for a course."
                redirect_to profile_path
            end
        else
            flash[:notice] = "Please log in as user to register for a course."
            redirect_to user_login_path
        end
    end
end

app/helpers/course_helper.rb
module CourseHelper
end

app/views/course/mcoursec.html.erb
<div class="form-page">
  <div class="form-container">
    <div class="form-header">
      <div class="greeting">नमस्ते 🙏</div>
      <h1>नूतनः पाठ्यक्रमः योजयतु</h1>
      <p class="form-subtitle">नवीन पाठ्यक्रमं सृजयतु</p>
    </div>

    <%= form_tag course_post_path, multipart: true, class: "modern-form" do %>
      <div class="form-group">
        <%= label_tag "शीर्षकं (Course Name)", nil, class: "form-label" %>
        <%= text_field_tag :name, nil, required: true, class: "form-input", placeholder: "Enter course name..." %>
      </div>

      <div class="form-group">
        <%= label_tag "Course Code", nil, class: "form-label" %>
        <%= text_field_tag :cname, nil, required: true, class: "form-input", placeholder: "e.g., CS101" %>
      </div>

      <div class="form-group">
        <%= label_tag "Registration Status", nil, class: "form-label" %>
        <div class="radio-group">
          <label class="radio-label">
            <%= radio_button_tag :regon, "on", false, class: "radio-input" %>
            <span class="radio-custom"></span>
            <span class="radio-text">Open</span>
          </label>
          
          <label class="radio-label">
            <%= radio_button_tag :regon, "off", true, class: "radio-input" %>
            <span class="radio-custom"></span>
            <span class="radio-text">Closed</span>
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag "Course Image", nil, class: "form-label" %>
        <div class="file-input-wrapper">
          <%= file_field_tag :image, required: true, class: "file-input", accept: "image/*", id: "course-image-input" %>
          <label for="course-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span id="image-file-name">चित्रं चिनोतु</span>
          </label>
        </div>
        <div id="image-preview" class="file-preview" style="display: none;">
          <span class="preview-icon">✓</span>
          <span class="preview-text"></span>
        </div>
        <small style="display: block; margin-top: 0.5rem; color: #5a6c7d;">Recommended: 1200x800px or 3:2 ratio</small>
      </div>

      <div class="form-group">
        <%= label_tag "Description", nil, class: "form-label" %>
        <%= text_area_tag :description, nil, required: true, class: "form-textarea", 
                          placeholder: "Write a brief description of the course...", rows: 5 %>
      </div>

      <div class="form-group">
        <%= label_tag "Additional Information", nil, class: "form-label" %>
        <%= text_area_tag :more, nil, required: true, class: "form-textarea", 
                          placeholder: "Add more details about the course (syllabus, objectives, etc.)...", rows: 6 %>
      </div>

      <div class="form-group">
        <%= label_tag "Lecture Links (Optional)", nil, class: "form-label" %>
        <%= text_area_tag :yt, nil, class: "form-textarea", 
                          placeholder: "Format:\nLecture 1: https://youtube.com/...\nLecture 2: https://youtube.com/...", rows: 4 %>
        <small style="display: block; margin-top: 0.5rem; color: #5a6c7d;">Add YouTube or video links for lectures, one per line</small>
      </div>

      <div class="form-actions">
        <%= submit_tag "अग्रेस्थापनं करोतु", class: "btn btn-primary" %>
        <%= link_to "प्रतिगच्छतु", all_courses_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const fileInput = document.getElementById('course-image-input');
  const fileName = document.getElementById('image-file-name');
  const preview = document.getElementById('image-preview');
  const previewText = preview.querySelector('.preview-text');
  
  fileInput.addEventListener('change', function() {
    if (this.files && this.files.length > 0) {
      const file = this.files[0];
      fileName.textContent = file.name;
      previewText.textContent = `चयनितं: ${file.name} (${(file.size / 1024 / 1024).toFixed(2)} MB)`;
      preview.style.display = 'flex';
    } else {
      fileName.textContent = 'चित्रं चिनोतु';
      preview.style.display = 'none';
    }
  });
});
</script>

app/views/course/mcourser.html.erb
<div class="admin-courses-page">
  <div class="admin-header">
    <h1>Course Management</h1>
    <p class="admin-subtitle">Manage and organize all courses</p>
    <%= link_to new_course_path, class: "btn-create" do %>
      <span class="btn-icon">+</span>
      नूतनः courseH योजयतु
    <% end %>
  </div>

  <div class="admin-courses-container">
    <% @courses.each do |course| %>
      <div class="admin-course-card">
        <div class="admin-course-image">
          <%= image_tag rails_blob_url(course.image), alt: course.name %>
        </div>

        <div class="admin-course-content">
          <h2 class="admin-course-title"><%= course.name %></h2>

          <div class="admin-course-info">
            <p><%= truncate(strip_tags(course.description), length: 100) %></p>
            <p><strong>Course code:</strong> <%= course.cname %></p>
            <p><strong>Registration:</strong> 
              <span style="color: <%= course.regon == 'on' ? '#52c41a' : '#ff4d4f' %>;">
                <%= course.regon.upcase %>
              </span>
            </p>

            <details style="margin-top: 1rem;">
              <summary style="cursor: pointer; font-weight: 600; color: #47596F; padding: 0.5rem 0;">
                📋 View Full Details
              </summary>
              <div style="margin-top: 1rem; padding: 1rem; background: #f8f9ff; border-radius: 6px; font-size: 0.9rem;">
                <%= course.more.html_safe %>
                
                <div style="margin-top: 1rem;">
                  <strong>Lecture Links:</strong>
                  <% if course.yt.present? %>
                    <ul style="margin: 0.5rem 0 0 1.5rem; padding: 0;">
                      <% course.yt.split("\n").first(3).each do |link| %>
                        <% lecture = link.split(": ") %>
                        <li style="margin-bottom: 0.3rem;">
                          <%= lecture[0] %>: <%= truncate(lecture[1], length: 30) %>
                        </li>
                      <% end %>
                      <% if course.yt.split("\n").length > 3 %>
                        <li style="color: #5a6c7d;">... and <%= course.yt.split("\n").length - 3 %> more</li>
                      <% end %>
                    </ul>
                  <% else %>
                    <p style="margin: 0.5rem 0 0; color: #5a6c7d;">Coming soon</p>
                  <% end %>
                </div>

                <div style="margin-top: 1rem;">
                  <strong>Exams:</strong>
                  <ul style="margin: 0.5rem 0 0 1.5rem; padding: 0;">
                    <% exam_count = 0 %>
                    <% @exams.each do |exam| %>
                      <% if exam.name.include?(course.cname) %>
                        <% exam_parts = exam.name.split("_") %>
                        <% type = exam.etype ? "Quiz" : "Exam" %>
                        <li style="margin-bottom: 0.3rem;">
                          <%= link_to ques_read_path(course.cname, exam_parts[0] + "_" + exam_parts[1]),
                                      style: "color: #47596F; text-decoration: none;" do %>
                            <%= "#{type} - #{exam_parts[1]}" %>
                          <% end %>
                        </li>
                        <% exam_count += 1 %>
                        <% break if exam_count >= 3 %>
                      <% end %>
                    <% end %>
                    <% if exam_count == 0 %>
                      <li style="color: #5a6c7d;">No exams yet</li>
                    <% end %>
                  </ul>
                </div>

                <%= link_to exam_new_path(course.cname), 
                            class: "btn-edit", 
                            style: "margin-top: 1rem; width: 100%; font-size: 0.75rem; height: 36px;" do %>
                  <span class="btn-icon">+</span>
                  Add Exam
                <% end %>
              </div>
            </details>
          </div>

          <div class="admin-course-actions" style="margin-top: 1.5rem;">
            <%= link_to mp_marks_path(course.cname), class: "btn-edit" do %>
              <span class="btn-icon">📊</span>
              Marks
            <% end %>

            <%= link_to course_path(course.id), class: "btn-edit" do %>
              <span class="btn-icon">✏️</span>
              Edit
            <% end %>
          </div>

          <div class="admin-course-actions">
            <%= button_to course_delete_path(course.id), 
                        method: "delete", 
                        data: { confirm: "Are you sure you want to delete this course?" },
                        class: "btn-delete" do %>
              <span class="btn-icon">🗑️</span>
              विनश्यतु
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/course/mcourseu.html.erb
<div class="form-page">
  <div class="form-container">
    <div class="form-header">
      <div class="greeting">नमस्ते 🙏</div>
      <h1>Course-परिवर्तनं करोतु</h1>
      <p class="form-subtitle">पाठ्यक्रमस्य सूचनां परिवर्तयतु</p>
    </div>

    <%= form_for @course, url: course_update_path, multipart: true, class: "modern-form" do |f| %>
      <div class="form-group">
        <%= f.label "शीर्षकं (Course Name)", class: "form-label" %>
        <%= f.text_field :name, required: true, class: "form-input", placeholder: "Enter course name..." %>
      </div>

      <div class="form-group">
        <%= f.label "Course Code", class: "form-label" %>
        <%= f.text_field :cname, required: true, class: "form-input", placeholder: "e.g., CS101" %>
      </div>

      <div class="form-group">
        <%= f.label "Registration Status", class: "form-label" %>
        <div class="radio-group">
          <label class="radio-label">
            <%= f.radio_button :regon, "on", class: "radio-input" %>
            <span class="radio-custom"></span>
            <span class="radio-text">Open</span>
          </label>
          
          <label class="radio-label">
            <%= f.radio_button :regon, "off", class: "radio-input" %>
            <span class="radio-custom"></span>
            <span class="radio-text">Closed</span>
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Description", class: "form-label" %>
        <%= f.text_area :description, required: true, class: "form-textarea", 
                        placeholder: "Write a brief description of the course...", rows: 5 %>
      </div>

      <div class="form-group">
        <%= f.label "Additional Information", class: "form-label" %>
        <%= f.text_area :more, required: true, class: "form-textarea", 
                        placeholder: "Add more details about the course (syllabus, objectives, etc.)...", rows: 6 %>
      </div>

      <div class="form-group">
        <%= f.label "Lecture Links (Optional)", class: "form-label" %>
        <%= f.text_area :yt, class: "form-textarea", 
                        placeholder: "Format:\nLecture 1: https://youtube.com/...\nLecture 2: https://youtube.com/...", rows: 4 %>
        <small style="display: block; margin-top: 0.5rem; color: #5a6c7d;">Add YouTube or video links for lectures, one per line</small>
      </div>

      <div class="form-group">
        <%= f.label "Current Image", class: "form-label" %>
        <div class="current-image">
          <%= image_tag rails_blob_url(@course.image), class: "preview-image", alt: @course.name %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Change Image (optional)", class: "form-label" %>
        <div class="file-input-wrapper">
          <%= f.file_field :image, accept: "image/*", class: "file-input", id: "course-update-image-input" %>
          <label for="course-update-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span>नवीनं चित्रं चिनोतु</span>
          </label>
        </div>
        <small style="display: block; margin-top: 0.5rem; color: #5a6c7d;">Leave empty to keep current image</small>
      </div>

      <div class="form-actions">
        <%= f.submit "अग्रेस्थापनं करोतु", class: "btn btn-primary" %>
        <%= link_to "प्रतिगच्छतु", all_courses_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  // Preview file name when selected
  document.getElementById('course-update-image-input').addEventListener('change', function(e) {
    const fileName = e.target.files[0]?.name;
    if (fileName) {
      const label = document.querySelector('.file-input-label span');
      label.textContent = fileName;
    }
  });
</script>

app/views/course/ucourse1.html.erb
<% course = @course %>

<div class="course-detail-page">
  <div class="course-detail-container">
    <div class="course-detail-header">
      <h1 class="course-detail-title"><%= course.name %></h1>
    </div>

    <div class="course-detail-image">
      <%= image_tag rails_blob_url(course.image), alt: course.name %>
    </div>

    <div class="course-detail-content">
      <%= course.description.html_safe %>

      <p style="margin-top: 2rem;">
        <strong>Course code:</strong> <%= course.cname %>
      </p>

      <%= course.more.html_safe %>

      <% if @user_regd > 0 %>
        <div class="registration-status">
          ✓ You are registered for this course
        </div>

        <div class="lecture-links">
          <h3>📚 Lecture Links</h3>
          <% if course.yt.present? %>
            <ul>
              <% course.yt.split("\n").each do |link| %>
                <% lecture = link.split(": ") %>
                <li>
                  <%= lecture[0] %>: 
                  <%= link_to lecture[1], lecture[1], target: "_blank" %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p>Coming soon.</p>
          <% end %>
        </div>

        <div class="exam-list">
          <h3>📝 Exams</h3>
          <ul>
            <% @exams.select { |e| e.name.include?(course.cname) }.each do |exam| %>
              <% exam_parts = exam.name.split("_") %>
              <% type = exam.etype ? "Self Evaluation Quiz" : "Main Exam" %>
              <li>
                <%= link_to exam_uview_path(course.cname, exam_parts[0] + "_" + exam_parts[1]) do %>
                  <%= "#{type} - #{exam_parts[1]} | #{exam_parts[2]}" %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

      <% elsif course.regon == "off" %>
        <div class="registration-closed">
          ⚠ Registration has been closed for this course
        </div>

      <% else %>
        <div style="text-align: center; margin-top: 2rem;">
          <%= link_to course_reg_path(course.cname), 
                      class: "btn-edit",
                      style: "display: inline-flex; width: 200px; margin: 0 auto;",
                      data: { confirm: "Are you sure you want to register for this course?" } do %>
            <span class="btn-icon">✓</span>
            Register Now
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="back-button">
      <%= link_to courses_path, class: "btn-secondary" do %>
        ← प्रतिगच्छतु
      <% end %>
    </div>
  </div>
</div>