config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'welcome#home'

    get "user/uprofile",                                                    as:"uprofile"
    get "user/muserr",                                                      as:"all_users"
    post "user/muserr",                                                     as:"user_sort"
    delete "user/:id/del",                          to:"user#muserdp",      as:"user_delete"
    get "user/uform",                                                       as:"form"
    patch "user/uformp",                                                    as:"form_post"
    
    get "welcome/mhomer",                                                   as:"home"
    get "welcome/mnewsc",                                                   as:"new_news"
    post "welcome/mnewscp",                                                 as:"news_post"
    get "news/:id/up",                              to:"welcome#mnewsu",    as:"news"
    patch "news/:id",                               to:"welcome#mnewsup",   as:"news_update"
    delete "news/:id/del",                          to:"welcome#mnewsdp",   as:"news_delete"

    get "welcome/about",                                                    as:"about"
    get "welcome/htuse",                                                    as:"htuse"
    get "welcome/terms",                                                    as:"terms"
    get "welcome/maboutu",                                                  as:"about_change"
    get "welcome/mhtuseu",                                                  as:"htuse_change"
    get "welcome/mtermsu",                                                  as:"terms_change"
    patch "welcome/maboutup",                                               as:"about_update"
    patch "welcome/mhtuseup",                                               as:"htuse_update"
    patch "welcome/mtermsup",                                               as:"terms_update"

    get "game/ugame",                                                       as:"games"
    get "game/uview/:id",                           to:"game#ugamen",       as:"game_uview"
    get "game/mgamer",                                                      as:"all_games"
    get "game/mgamec",                                                      as:"new_game"
    post "game/mgamecp",                                                    as:"game_post"
    get "game/:id/up",                              to:"game#mgameu",       as:"game"
    patch "game/:id",                                to:"game#mgameup",      as:"game_update"
    delete "game/:id/del",                          to:"game#mgamedp",      as:"game_delete"

    get "logging/mnew",                                                     as:"new_member"
    get "logging/unew",                                                     as:"new_user"
    post "logging/newp",                                                    as:"newp"
    post "logging/otpp",                                                    as:"otpp"
    get "logging/mlogin",                                                   as:"member_login"
    get "logging/ulogin",                                                   as:"user_login"
    post "logging/loginp",                                                  as:"login_post"
    get "logging/logout",                                                   as:"logout"
    get "logging/forgot",                                                   as:"forgot"
    post "logging/forgotp",                                                 as:"forgotp"
    post "logging/resetp",                                                  as:"resetp"
    get "reset_otp",                             to: "logging#reset_otp",  as: "reset_otp"

    get "course/ucourse",                                                   as:"courses"
    get "course/mcourser",                                                  as:"all_courses"
    get "course/mcoursec",                                                  as:"new_course"
    post "course/mcoursecp",                                                as:"course_post"
    get "course/:id/up",                            to:"course#mcourseu",   as:"course"
    patch "course/:id",                             to:"course#mcourseup",  as:"course_update"
    delete "course/:id/del",                        to:"course#mcoursedp",  as:"course_delete"
    get "course/:cname/uview",                      to:"course#ucourse1",   as:"course_uview"
    get "course/:cname/reg",                        to:"course#ureg",       as:"course_reg"
    # post "course/:name/reg",                      to:"course#uformp"

    get "feedback/ufeedback",                                               as:"feedback"
    post "feedback/ufeedbackp",                                             as:"feedback_post"
    get "feedback/mfeedbackr",                                              as:"all_feedbacks"

    get "shlok/ushlok",                                                     as:"shloks"
    get "shlok/mshlokr",                                                    as:"all_shloks"
    get "shlok/mshlokc",                                                    as:"new_shlok"
    post "shlok/mshlokcp",                                                  as:"shlok_post"
    get "shlok/:id/up",                             to:"shlok#mshloku",     as:"shlok"
    patch "shlok/:id",                              to:"shlok#mshlokup",    as:"shlok_update"
    delete "shlok/:id/del",                         to:"shlok#mshlokdp",    as:"shlok_delete"

    get "event/uevent",                                                     as:"events"
    get "event/meventr",                                                    as:"all_events"
    get "event/meventc",                                                    as:"new_event"
    post "event/meventcp",                                                  as:"event_post"
    get "event/:id/up",                             to:"event#meventu",     as:"event"
    patch "event/:id",                              to:"event#meventup",    as:"event_update"
    delete "event/:id/del",                         to:"event#meventdp",    as:"event_delete"
    get 'event/uview/:id', to: 'event#ueventn', as: 'event_uview'


    get "resource/uresource",                                                     as:"resources"
    get "resource/mresourcer",                                                    as:"all_resources"
    get "resource/mresourcec",                                                    as:"new_resource"
    post "resource/mresourcecp",                                                  as:"resource_post"
    get "resource/:id/up",                             to:"resource#mresourceu",     as:"resource"
    patch "resource/:id",                              to:"resource#mresourceup",    as:"resource_update"
    delete "resource/:id/del",                         to:"resource#mresourcedp",    as:"resource_delete"

    get "exam/:cname/:ename/uview",                 to:"exam#uexam1",       as:"exam_uview"
    post "exam/:cname/:ename/upost",                to:"exam#uexamp",       as:"exam_upost"
    get "exam/:cname/new",                          to:"exam#mexamc",       as:"exam_new"
    post "exam/:cname/create",                      to:"exam#mexamcp",      as:"exam_create"
    get "exam/:cname/:ename/ch",                    to:"exam#mexamu",       as:"exam_change"
    patch "exam/:cname/:ename/up",                  to:"exam#mexamup",      as:"exam_update"
    delete "exam/:cname/:ename/del",                to:"exam#mexamdp",      as:"exam_delete"
    get "exam/:cname/:ename/r",                     to:"exam#mquescr",      as:"ques_read"
    post "exam/:cname/:ename/c",                    to:"exam#mquescr",      as:"ques_create"
    get "exam/:cname/:ename/:qno/ch",               to:"exam#mquesu",       as:"ques_change"
    patch "exam/:cname/:ename/:qno/up",             to:"exam#mquesup",      as:"ques_update"
    delete "exam/:cname/:ename/:qno/del",           to:"exam#mquesdp",      as:"ques_delete"

    get "member/uteam",                                                     as:"members"
    get "member/mmemberr",                                                  as:"all_members"
    get "member/:id/up",                            to:"member#mmemberu",   as:"member"
    patch "member/:id",                             to:"member#mmemberup",  as:"member_update"
    delete "member/:id/del",                        to:"member#mmemberdp",  as:"member_delete"
    get "member/memarea",                                                   as:"member_area"
    get "member/mprofile",                                                  as:"mprofile"
    get "member/mchanger",                                                  as:"all_changes"
    get "member/msql",                                                      as:"msql"
    post "member/msql",                                                     as:"exec_sql"

    get "exam/:cname/:ename/re_marks",              to:"exam#re_marks",     as:"re_marks"
    get "exam/:cname/mp_marks",                     to:"exam#mp_marks",     as:"mp_marks"

    get "library/ulibrary",                                                     as:"librarys"
    get "library/mlibraryr",                                                    as:"all_librarys"
    get "library/mlibraryc",                                                    as:"new_library"
    post "library/mlibrarycp",                                                  as:"library_post"
    get "library/:id/up",                             to:"library#mlibraryu",     as:"library"
    patch "library/:id",                              to:"library#mlibraryup",    as:"library_update"

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        @news = Announcement.order(created_at: :desc)
        @visit = session[:visit]
    end

    def mhomer
        if session[:member]
            @news = Announcement.order(created_at: :desc)
            @visit = session[:visit]
            render "mhomer"
        else
            redirect_to root_url
        end
    end

    def mnewsc
        if session[:member]
            render "mnewsc"
        else
            redirect_to root_url
        end
    end

    def mnewscp
        news = Announcement.new(:news => params[:news])
        news.save
        change = Change.new(:time => Time.now, :email => session[:email], :table => "announcements", :cord => "create")
        change.save
        flash[:notice] = "नूतनः announcementH योजितः जातः!"
        redirect_to home_path
    end

    def mnewsu
        if session[:member]
            @news = Announcement.find(params[:id])
            render "mnewsu"
        else
            redirect_to root_url
        end
    end

    def mnewsup
        news = Announcement.find(params[:id])
        news.update(:news => params[:announcement][:news])
        change = Change.new(:time => Time.now, :email => session[:email], :table => "announcements", :cord => "update")
        change.save
        flash[:notice] = "announcementH परिवर्तितः जातः!"
        redirect_to home_path
    end

    def mnewsdp
        news = Announcement.find(params[:id])
        news.destroy
        change = Change.new(:time => Time.now, :email => session[:email], :table => "announcements", :cord => "delete")
        change.save
        redirect_to home_path
    end

    def about
        @about = About.first&.about || "About content not available"
        render "abouts"
    end

    def htuse
        @htuse = About.first&.htuse || "How to use content not available"
        render "abouts"
    end

    def terms
        @terms = About.first&.terms || "Terms content not available"
        render "abouts"
    end

    def maboutu
        if session[:member]
            @about = About.first_or_create(about: "", htuse: "", terms: "")
            render "maboutsu"
        else
            redirect_to root_url
        end
    end

    def mhtuseu
        if session[:member]
            @htuse = About.first_or_create(about: "", htuse: "", terms: "")
            render "maboutsu"
        else
            redirect_to root_url
        end
    end

    def mtermsu
        if session[:member]
            @terms = About.first_or_create(about: "", htuse: "", terms: "")
            render "maboutsu"
        else
            redirect_to root_url
        end
    end

    def maboutup
        if session[:member]
            pp = params[:about]
            about = About.first
            about.update(:about => pp[:about])
            change = Change.new(:time => Time.now, :email => session[:email], :table => "abouts_a", :cord => "update")
            change.save
            redirect_to about_path
        else
            redirect_to root_url
        end
    end

    def mhtuseup
        if session[:member]
            pp = params[:about]
            htuse = About.first
            htuse.update(:htuse => pp[:htuse])
            change = Change.new(:time => Time.now, :email => session[:email], :table => "abouts_h", :cord => "update")
            change.save
            redirect_to htuse_path
        else
            redirect_to root_url
        end
    end

    def mtermsup
        if session[:member]
            pp = params[:about]
            terms = About.first
            terms.update(:terms => pp[:terms])
            change = Change.new(:time => Time.now, :email => session[:email], :table => "abouts_t", :cord => "update")
            change.save
            redirect_to terms_path
        else
            redirect_to root_url
        end
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/abouts.html.erb
<section class="m-content-container">
  <div class="m-content-wrapper">
    <div class="m-content-section m-visible">
      <div class="m-heading-section">
        <h1><%= @about ? "ABOUT SANSKRIT CLUB IITR" : @htuse ? "HOW TO USE" : "TERMS & CONDITIONS" %></h1>
        <span class="m-strip"></span>
      </div>

      <div class="m-content-text">
        <%= @about.html_safe if @about %>
        <%= @htuse.html_safe if @htuse %>
        <%= @terms.html_safe if @terms %>
      </div>

      <% if session[:member] %>
        <% path = @about ? about_change_path : @htuse ? htuse_change_path : terms_change_path %>
        <div class="m-content-button-wrapper">
          <%= link_to path, class: "m-anone" do %>
            <div class="m-button m-button-primary">परिवर्तयतु</div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const contentSection = document.querySelector('.m-content-section');
  if (contentSection) {
    contentSection.classList.add('m-visible');
  }
});
</script>

app/views/welcome/home.html.erb
<!-- First Section: About Us + Welcome Boxes -->
<section class="grid-container">
  <div class="left-section">
    <div class="heading-section">
      <h1>ABOUT US</h1>
      <span class="strip"></span>
    </div>

    <div class="content-block">
      <p class="sanskrit-text">
        संस्कृत-मण्डलः संस्कृतभाषायाः पुनरुत्थानस्य संवर्धनस्य च कृते कश्चन उपक्रमः वर्तते।
      </p>
      <p class="english-text">
        The Sanskrit Club is an initiative to revive and promote the bedrock for the growth of a large part of the glorious Indian Civilisation, the Sanskrit language.
      </p>
    </div>
  </div>

  <div class="right-section">
    <div class="grid-wrapper">
      <h1 class="box-text">नमो नमः!<br/>NAMO NAMAH!</h1>
      <span class="box bluish"></span>
    </div>

    <div class="grid-wrapper">
      <h1 class="box-text">संस्कृत-मण्डले सुस्वागतम्<br/>Welcome to Sanskrit Club</h1>
      <span class="box brownish"></span>
    </div>
  </div>
</section>

<!-- Second Section: Announcements with Verse on Left -->
<section class="announcements-container">
  <div class="announcements-grid-layout">
    <!-- Left Side: Sanskrit Verse -->
    <div class="verse-section">
      <div class="verse-sanskrit">
      <p>जाड्यं धियो हरति सिंचति वाचि सत्यं,</p>
      <p>मानोन्नतिं दिशति पापमपाकरोति |</p>
      <p>चेतः प्रसादयति दिक्षु तनोति कीर्तिं,</p>
      <p>सत्संगतिः कथय किं न करोति पुंसाम् ||</p>
      </div>
      <p class="verse-hindi">
        (अच्छे मित्रों का साथ बुद्धि की जड़ता को हर लेता है, वाणी में सत्य का संचार करता है, मान और उन्नति को बढ़ाता है और पाप से मुक्त करता है। चित्त को प्रसन्न करता है और हमारी कीर्ति को सभी दिशाओं में फैलाता है। आप ही कहें कि सत्संगति मनुष्यों के भले के लिये क्या नहीं करती!)
      </p>
    </div>

    <!-- Right Side: Announcements -->
    <div class="announcement-section">
      <div class="heading-section">
        <h1>NOTICEBOARD</h1>
        <span class="strip"></span>
      </div>

      <div class="announcement-list">
        <% if @news.present? %>
          <% @news.each do |i| %>
            <div class="announcement-box">
              <%= i.news.html_safe %>
            </div>
          <% end %>
        <% else %>
          <p class="no-announcements">No announcements at the moment.</p>
        <% end %>
      </div>

      <p class="visit-counter">
        You have visited this page <b><%= @visit %></b> times.
      </p>
    </div>
  </div>
</section>

<script>
// Parallax Scroll Effect for Sanskrit Club

document.addEventListener('DOMContentLoaded', function() {
  // Intersection Observer for fade-in animations
  const observerOptions = {
    threshold: 0.1,
    rootMargin: '0px 0px -100px 0px'
  };

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
      }
    });
  }, observerOptions);

  // Observe verse section
  const verseSection = document.querySelector('.verse-section');
  if (verseSection) {
    observer.observe(verseSection);
  }

  // Observe announcement section
  const announcementSection = document.querySelector('.announcement-section');
  if (announcementSection) {
    observer.observe(announcementSection);
  }

  // Observe each announcement box with staggered delay
  const announcementBoxes = document.querySelectorAll('.announcement-box');
  announcementBoxes.forEach((box, index) => {
    box.style.transitionDelay = `${index * 0.3}s`;
    observer.observe(box);
  });

  // Smooth scroll to announcements when scroll indicator is clicked
  const gridContainer = document.querySelector('.grid-container');
  if (gridContainer) {
    gridContainer.addEventListener('click', function(e) {
      if (e.target === this || e.target.textContent === '↓') {
        const announcementsContainer = document.querySelector('.announcements-container');
        if (announcementsContainer) {
          announcementsContainer.scrollIntoView({ 
            behavior: 'smooth',
            block: 'start'
          });
        }
      }
    });
  }

  // Optional: Parallax effect on scroll
  window.addEventListener('scroll', function() {
    const scrolled = window.pageYOffset;
    const gridContainer = document.querySelector('.grid-container');
    
    if (gridContainer && scrolled < window.innerHeight) {
      // Subtle parallax movement for the first section
      gridContainer.style.transform = `translateY(${scrolled * 0.3}px)`;
      gridContainer.style.opacity = 1 - (scrolled / window.innerHeight);
    }
  });
});
</script>

app/views/welcome/maboutsu.html.erb
<section class="m-form-container">
  <div class="m-form-wrapper">
    <div class="m-form-section m-visible">
      <div class="m-heading-section">
        <h1><%= @about ? "UPDATE ABOUT" : @htuse ? "UPDATE HOW TO USE" : "UPDATE TERMS" %></h1>
        <span class="m-strip"></span>
      </div>

      <% path = @about ? about_update_path : @htuse ? htuse_update_path : terms_update_path %>
      <% about = @about ? @about : @htuse ? @htuse : @terms %>
      <% field = @about ? :about : @htuse ? :htuse : :terms %>
      <% back = @about ? about_path : @htuse ? htuse_path : terms_path %>

      <%= form_for about, url: path do |f| %>
        <div class="m-form-field">
          <%= f.label field.to_s.titleize, nil, class: "m-form-label" %>
          <%= f.text_area field, 
              required: true, 
              rows: 10,
              class: "m-form-textarea" %>
        </div>

        <div class="m-form-buttons">
          <%= f.submit "अग्रेस्थापनं करोतु", class: "m-button m-button-primary" %>
          <%= link_to "प्रतिगच्छतु", back, class: "m-button m-button-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const formSection = document.querySelector('.m-form-section');
  if (formSection) {
    formSection.classList.add('m-visible');
  }
});
</script>

app/views/welcome/memarea.html.erb
<div>
    <div class="button">
        <%= link_to "All users", all_users_path, class: "anone" %>
    </div>
    <div class="button">
        <%= link_to "New member", new_member_path, class: "anone" %>
    </div>
    <div class="button">
        <%= link_to "Profile", mprofile_path, class: "anone" %>
    </div>
    <% if session[:member] %>
    <div class="button">
        <%= link_to "All Members", all_teams_path, class: "anone" %>
    </div>
    <% end %>
    <div class="button">
        <%= link_to "Execute SQL", form_path, class: "anone" %>
    </div>
</div>

app/views/welcome/mhomec.html.erb
<%= form_tag announcement_post_path do %>
    <br/>
    <%= label_tag "Announcement" %><br/>
    <%= text_field_tag :news, nil, :required => true, class: "mtextfield" %><br/><br/>
    <%= submit_tag "अग्रेस्थापनं करोतु", :class => "button" %><br/>
    <%= link_to "प्रतिगच्छतु", home_path %>
<% end %>

app/views/welcome/mhomer.html.erb
<!-- First Section: About Us + Welcome Boxes -->
<section class="m-grid-container">
  <div class="m-left-section">
    <div class="m-heading-section">
      <h1>ABOUT US</h1>
      <span class="m-strip"></span>
    </div>

    <div class="m-content-block">
      <p class="m-sanskrit-text">
        संस्कृत-मण्डलः संस्कृतभाषायाः पुनरुत्थानस्य संवर्धनस्य च कृते कश्चन उपक्रमः वर्तते।
      </p>
      <p class="m-english-text">
        The Sanskrit Club is an initiative to revive and promote the bedrock for the growth of a large part of the glorious Indian Civilisation, the Sanskrit language.
      </p>
    </div>
  </div>

  <div class="m-right-section">
    <div class="m-grid-wrapper">
      <h1 class="m-box-text">नमो नमः!<br/>NAMO NAMAH!</h1>
      <span class="m-box m-bluish"></span>
    </div>

    <div class="m-grid-wrapper">
      <h1 class="m-box-text">संस्कृत-मण्डले सुस्वागतम्<br/>Welcome to Sanskrit Club</h1>
      <span class="m-box m-brownish"></span>
    </div>
  </div>
</section>

<!-- Second Section: Announcements with Verse on Left -->
<section class="m-announcements-container">
  <div class="m-announcements-grid-layout">
    <!-- Left Side: Sanskrit Verse -->
    <div class="m-verse-section">
      <p class="m-verse-sanskrit">
        जाड्यं धियो हरति सिंचति वाचि सत्यं,<br/>
        मानोन्नतिं दिशति पापमपाकरोति |<br/>
        चेतः प्रसादयति दिक्षु तनोति कीर्तिं,<br/>
        सत्संगतिः कथय किं न करोति पुंसाम् ||
      </p>
      <p class="m-verse-hindi">
        (अच्छे मित्रों का साथ बुद्धि की जड़ता को हर लेता है, वाणी में सत्य का संचार करता है, मान और उन्नति को बढ़ाता है और पाप से मुक्त करता है। चित्त को प्रसन्न करता है और हमारी कीर्ति को सभी दिशाओं में फैलाता है। आप ही कहें कि सत्संगति मनुष्यों के भले के लिये क्या नहीं करती!)
      </p>
    </div>

    <!-- Right Side: Announcements -->
    <div class="m-announcement-section">
      <div class="m-heading-section">
        <h1>ANNOUNCEMENTS</h1>
        <span class="m-strip"></span>
      </div>

      <%= link_to new_news_path, class: "m-ann-button" do %>
        <span>नूतनं घोषणां योजयतु</span>
        <span class="m-plus-icon">+</span>
      <% end %>      
      <div class="m-announcement-list">
        <% if @news.present? %>
          <% @news.each do |i| %>
            <div class="m-announcement-box">
              <div class="m-announcement-content">
                <%= i.news.html_safe %>
              </div>
              <div class="m-updel">
                <%= link_to news_path(i.id), class: "m-anone" do %>
                  <div class="m-edit-button">परिवर्तयतु</div>
                <% end %>
                <%= button_to news_delete_path(i.id), method: "delete",
                    data: {confirm: "Are you sure you want to delete this announcement?"}, class: "m-anone" do %>
                  <div class="m-delete-button">विनश्यतु</div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="m-no-announcements">No announcements at the moment.</p>
        <% end %>
      </div>

      <p class="m-visit-counter">
        You have visited this page <b><%= @visit %></b> times.
      </p>
    </div>
  </div>
</section>

<script>
// Parallax Scroll Effect for Sanskrit Club - mhomer version

document.addEventListener('DOMContentLoaded', function() {
  // Intersection Observer for fade-in animations
  const observerOptions = {
    threshold: 0.1,
    rootMargin: '0px 0px -100px 0px'
  };

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('m-visible');
      }
    });
  }, observerOptions);

  // Observe verse section
  const verseSection = document.querySelector('.m-verse-section');
  if (verseSection) {
    observer.observe(verseSection);
  }

  // Observe announcement section
  const announcementSection = document.querySelector('.m-announcement-section');
  if (announcementSection) {
    observer.observe(announcementSection);
  }

  // Observe each announcement box with staggered delay
  const announcementBoxes = document.querySelectorAll('.m-announcement-box');
  announcementBoxes.forEach((box, index) => {
    box.style.transitionDelay = `${index * 0.15}s`;
    observer.observe(box);
  });

  // Smooth scroll to announcements when scroll indicator is clicked
  const gridContainer = document.querySelector('.m-grid-container');
  if (gridContainer) {
    gridContainer.addEventListener('click', function(e) {
      if (e.target === this || e.target.textContent === '↓') {
        const announcementsContainer = document.querySelector('.m-announcements-container');
        if (announcementsContainer) {
          announcementsContainer.scrollIntoView({ 
            behavior: 'smooth',
            block: 'start'
          });
        }
      }
    });
  }

  // Optional: Parallax effect on scroll
  window.addEventListener('scroll', function() {
    const scrolled = window.pageYOffset;
    const gridContainer = document.querySelector('.m-grid-container');
    
    if (gridContainer && scrolled < window.innerHeight) {
      // Subtle parallax movement for the first section
      gridContainer.style.transform = `translateY(${scrolled * 0.3}px)`;
      gridContainer.style.opacity = 1 - (scrolled / window.innerHeight);
    }
  });
});
</script>

app/views/welcome/mhomeu.html.erb
<div>
<p>welcome to mhomeu</p>
</div>
<%= form_for @news, url:announcement_update_path do |f| %>
    <%= f.label "announcement" %><br/>
    <%= f.text_field :news, :required => true, class: "mtextfield" %><br/>
    <%= f.submit "अग्रेस्थापनं करोतु", :class => "button" %><br/>
    <%= link_to "प्रतिगच्छतु", home_path %>
<% end %>

app/views/welcome/mnewsc.html.erb
<section class="m-announcements-container">
  <div class="m-announcements-grid-layout">
    <div class="m-announcement-section m-visible">
      <div class="m-heading-section">
        <h1>NEW NOTICE</h1>
        <span class="m-strip"></span>
      </div>

      <%= form_tag news_post_path do %>
        <div style="margin: 2rem 0;">
          <%= label_tag "Announcement", nil, style: "font-family: 'Saira'; font-size: 24px; color: #312229; display: block; margin-bottom: 1rem;" %>
          <%= text_area_tag :news, nil, 
              required: true, 
              rows: 6,
              style: "width: 100%; padding: 1rem; font-family: 'Hind'; font-size: 18px; border: 2px solid #b18653; border-radius: 6px; resize: vertical; box-sizing: border-box;" %>
        </div>

        <div style="display: flex; gap: 1rem; margin-top: 2rem; align-items: center; justify-content: flex-start;">
          <%= submit_tag "अग्रेस्थापनं करोतु", class: "m-button", style: "background-color: #54101d; color: white; padding: 0.75rem 2rem; font-size: 1rem; border: none; border-radius: 6px; cursor: pointer; font-family: inherit; line-height: normal;" %>
          <%= link_to "प्रतिगच्छतु", home_path, class: "m-button", style: "background-color: #b18653; color: white; padding: 0.75rem 2rem; font-size: 1rem; border: none; border-radius: 6px; cursor: pointer; text-align: center; text-decoration: none; display: inline-block; font-family: inherit; line-height: normal; box-sizing: border-box;" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script>
document.addEventListener('DOMContentLoaded', function() {
  // Make section visible immediately
  const announcementSection = document.querySelector('.m-announcement-section');
  if (announcementSection) {
    announcementSection.classList.add('m-visible');
  }
});
</script>

app/views/welcome/mnewsu.html.erb
<section class="m-announcements-container">
  <div class="m-announcements-grid-layout">
    <div class="m-announcement-section m-visible">
      <div class="m-heading-section">
        <h1>UPDATE NOTICE</h1>
        <span class="m-strip"></span>
      </div>

      <%= form_for @news, url: news_update_path do |f| %>
        <div style="margin: 2rem 0;">
          <%= f.label "Announcement", nil, style: "font-family: 'Saira'; font-size: 24px; color: #312229; display: block; margin-bottom: 1rem;" %>
          <%= f.text_area :news, 
              required: true, 
              rows: 6,
              style: "width: 100%; padding: 1rem; font-family: 'Hind'; font-size: 18px; border: 2px solid #b18653; border-radius: 6px; resize: vertical; box-sizing: border-box;" %>
        </div>

        <div style="display: flex; gap: 1rem; margin-top: 2rem;">
          <%= f.submit "अग्रेस्थापनं करोतु", class: "m-button" , style: "background-color: #54101d; color: white"%>
          <%= link_to "प्रतिगच्छतु", home_path, class: "m-button", style: "background-color: #b18653; color: white" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script>
document.addEventListener('DOMContentLoaded', function() {
  // Make section visible immediately
  const announcementSection = document.querySelector('.m-announcement-section');
  if (announcementSection) {
    announcementSection.classList.add('m-visible');
  }
});
</script>

app/views/welcome/profile.html.erb
<% link_to "प्रतिगछतु", root_url %><br/>
<div>
    Name: <%= @user.name %><br/>
    Email: <%= @user.email %><br/>
    Courses registered in: Subhashitam Samskritam
</div>