config/routes.rb
    get "welcome/htuse",                                                    as:"htuse"
    get "welcome/terms",                                                    as:"terms"
    get "welcome/maboutu",                                                  as:"about_change"
    get "welcome/mhtuseu",                                                  as:"htuse_change"
    get "welcome/mtermsu",                                                  as:"terms_change"
    patch "welcome/maboutup",                                               as:"about_update"
    patch "welcome/mhtuseup",                                               as:"htuse_update"
    patch "welcome/mtermsup",                                               as:"terms_update"

    get "game/ugame",                                                       as:"games"
    get "game/uview/:id",                           to:"game#ugamen",       as:"game_uview"
    get "game/mgamer",                                                      as:"all_games"
    get "game/mgamec",                                                      as:"new_game"
    post "game/mgamecp",                                                    as:"game_post"
    get "game/:id/up",                              to:"game#mgameu",       as:"game"
    patch "game/:id",                                to:"game#mgameup",      as:"game_update"
    delete "game/:id/del",                          to:"game#mgamedp",      as:"game_delete"

    get "logging/mnew",                                                     as:"new_member"
    get "logging/unew",                                                     as:"new_user"
    post "logging/newp",                                                    as:"newp"
    post "logging/otpp",                                                    as:"otpp"
    get "logging/mlogin",                                                   as:"member_login"
    get "logging/ulogin",                                                   as:"user_login"
    post "logging/loginp",                                                  as:"login_post"
    get "logging/logout",                                                   as:"logout"
    get "logging/forgot",                                                   as:"forgot"
    post "logging/forgotp",                                                 as:"forgotp"
    post "logging/resetp",                                                  as:"resetp"
    get "reset_otp",                             to: "logging#reset_otp",  as: "reset_otp"

    get "course/ucourse",                                                   as:"courses"
    get "course/mcourser",                                                  as:"all_courses"
    get "course/mcoursec",                                                  as:"new_course"
    post "course/mcoursecp",                                                as:"course_post"
    get "course/:id/up",                            to:"course#mcourseu",   as:"course"
    patch "course/:id",                             to:"course#mcourseup",  as:"course_update"
    delete "course/:id/del",                        to:"course#mcoursedp",  as:"course_delete"
    get "course/:cname/uview",                      to:"course#ucourse1",   as:"course_uview"
    get "course/:cname/reg",                        to:"course#ureg",       as:"course_reg"
    # post "course/:name/reg",                      to:"course#uformp"

    get "feedback/ufeedback",                                               as:"feedback"
    post "feedback/ufeedbackp",                                             as:"feedback_post"
    get "feedback/mfeedbackr",                                              as:"all_feedbacks"

    get "shlok/ushlok",                                                     as:"shloks"
    get "shlok/mshlokr",                                                    as:"all_shloks"
    get "shlok/mshlokc",                                                    as:"new_shlok"
    post "shlok/mshlokcp",                                                  as:"shlok_post"
    get "shlok/:id/up",                             to:"shlok#mshloku",     as:"shlok"
    patch "shlok/:id",                              to:"shlok#mshlokup",    as:"shlok_update"
    delete "shlok/:id/del",                         to:"shlok#mshlokdp",    as:"shlok_delete"

    get "event/uevent",                                                     as:"events"
    get "event/meventr",                                                    as:"all_events"
    get "event/meventc",                                                    as:"new_event"
    post "event/meventcp",                                                  as:"event_post"
    get "event/:id/up",                             to:"event#meventu",     as:"event"
    patch "event/:id",                              to:"event#meventup",    as:"event_update"
    delete "event/:id/del",                         to:"event#meventdp",    as:"event_delete"
    get 'event/uview/:id', to: 'event#ueventn', as: 'event_uview'


    get "resource/uresource",                                                     as:"resources"
    get "resource/mresourcer",                                                    as:"all_resources"
    get "resource/mresourcec",                                                    as:"new_resource"
    post "resource/mresourcecp",                                                  as:"resource_post"
    get "resource/:id/up",                             to:"resource#mresourceu",     as:"resource"
    patch "resource/:id",                              to:"resource#mresourceup",    as:"resource_update"
    delete "resource/:id/del",                         to:"resource#mresourcedp",    as:"resource_delete"

    get "exam/:cname/:ename/uview",                 to:"exam#uexam1",       as:"exam_uview"
    post "exam/:cname/:ename/upost",                to:"exam#uexamp",       as:"exam_upost"
    get "exam/:cname/new",                          to:"exam#mexamc",       as:"exam_new"
    post "exam/:cname/create",                      to:"exam#mexamcp",      as:"exam_create"
    get "exam/:cname/:ename/ch",                    to:"exam#mexamu",       as:"exam_change"
    patch "exam/:cname/:ename/up",                  to:"exam#mexamup",      as:"exam_update"
    delete "exam/:cname/:ename/del",                to:"exam#mexamdp",      as:"exam_delete"
    get "exam/:cname/:ename/r",                     to:"exam#mquescr",      as:"ques_read"
    post "exam/:cname/:ename/c",                    to:"exam#mquescr",      as:"ques_create"
    get "exam/:cname/:ename/:qno/ch",               to:"exam#mquesu",       as:"ques_change"
    patch "exam/:cname/:ename/:qno/up",             to:"exam#mquesup",      as:"ques_update"
    delete "exam/:cname/:ename/:qno/del",           to:"exam#mquesdp",      as:"ques_delete"

    get "member/uteam",                                                     as:"members"
    get "member/mmemberr",                                                  as:"all_members"
    get "member/:id/up",                            to:"member#mmemberu",   as:"member"
    patch "member/:id",                             to:"member#mmemberup",  as:"member_update"
    delete "member/:id/del",                        to:"member#mmemberdp",  as:"member_delete"
    get "member/memarea",                                                   as:"member_area"
    get "member/mprofile",                                                  as:"mprofile"
    get "member/mchanger",                                                  as:"all_changes"
    get "member/msql",                                                      as:"msql"
    post "member/msql",                                                     as:"exec_sql"

    get "exam/:cname/:ename/re_marks",              to:"exam#re_marks",     as:"re_marks"
    get "exam/:cname/mp_marks",                     to:"exam#mp_marks",     as:"mp_marks"

    get "library/ulibrary",                                                     as:"librarys"
    get "library/mlibraryr",                                                    as:"all_librarys"
    get "library/mlibraryc",                                                    as:"new_library"
    post "library/mlibrarycp",                                                  as:"library_post"
    get "library/:id/up",                             to:"library#mlibraryu",     as:"library"
    patch "library/:id",                              to:"library#mlibraryup",    as:"library_update"
    delete "library/:id/del",                         to:"library#mlibrarydp",    as:"library_delete"
    
    get "team/uteam",                                                       as:"teams"
    get "team/mteamr",                                                      as:"all_teams"
    get "team/mteamc",                                                      as:"new_team"
    post "team/mteamcp",                                                    as:"team_post"
    get "team/:id/up",                              to:"team#mteamu",       as:"team"
    patch "team/:id",                               to:"team#mteamup",      as:"team_update"
    delete "team/:id/del",                          to:"team#mteamdp",      as:"team_delete"
    
    # Group Photos routes
    get "team/mgroupr",                             to:"team#mgroup_photos",        as:"group_photos"
    post "team/mgroupcp",                           to:"team#mgroup_photo_create",  as:"mgroup_photo_create"
    delete "team/group/:id/del",                    to:"team#mgroup_photo_delete",  as:"delete_group_photo"

     # Alumni routes - using TeamController
     post "alumni/malumnicp",                        to:"team#malumnicp",    as:"alumni_post"
     get "alumni/:id/up",                            to:"team#malumniu",     as:"alumni"
     patch "alumni/:id",                             to:"team#malumniup",    as:"alumni_update"

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def uteam
        @teams = Team.all.order(id: :desc)
        @alumnis = Alumni.all.order(name: :asc)
        @group_photos = GroupPhoto.all.order(created_at: :desc).map { |gp| gp.image if gp.image.attached? }.compact
        render "uteam"
    end

    def mteamr
        if session[:member]
            @teams = Team.all.order(id: :desc)
            @alumnis = Alumni.all.order(created_at: :desc)  # ADD THIS LINE
            render "mteamr"
        else
            redirect_to root_url
        end
    end

    def mteamc
        if session[:member]
            render "mteamc"
        else
            redirect_to root_url
        end
    end    

    def mteamcp
        if session[:member]
            team = Team.new(:name => params[:name], :year => params[:year], :branch => params[:branch], :mail => params[:mail], :image => params[:image])
            team.save
            change = Change.new(:time => Time.now, :email => session[:email], :table => "teams", :cord => "create")
            change.save
            flash[:notice] = "नूतनः सदस्यः योजितः जातः!"
            redirect_to all_teams_path
        else
            redirect_to root_url
        end
    end

    def mteamu
        if session[:member]
            @id = params[:id]
            @team = Team.find_by(id: @id)
            render "mteamu"
        else
            redirect_to root_url
        end
    end

    def mteamup
        if session[:member]
            team = Team.find(params[:id])
            pp = params[:team]
            team.update(:name => pp[:name], :year => pp[:year], :branch => pp[:branch], :mail => pp[:mail])
            if pp[:image].present?
                team.image.purge
                team.image.attach(pp[:image])
            end
            change = Change.new(:time => Time.now, :email => session[:email], :table => "teams", :cord => "update")
            change.save
            flash[:notice] = "सदस्यः परिवर्तितः जातः!"
            redirect_to all_teams_path
        else
            redirect_to root_url
        end
    end

    def mteamdp
        if session[:member]
            team = Team.find(params[:id])
            team.destroy
            change = Change.new(:time => Time.now, :email => session[:email], :table => "teams", :cord => "delete")
            change.save
            flash[:notice] = "सदस्यः विलोपितः जातः!"
            redirect_to all_teams_path
        else
            redirect_to root_url
        end
    end

    def mgroup_photos
        if session[:member]
            @group_photos = GroupPhoto.all.order(created_at: :desc)
            render "mgroup_photos"
        else
            redirect_to root_url
        end
    end

    def mgroup_photo_create
        if session[:member]
            group_photo = GroupPhoto.new(image: params[:image])
            if group_photo.save
                change = Change.new(time: Time.now, email: session[:email], table: "group_photos", cord: "create")
                change.save
                flash[:notice] = "समूह चित्रं योजितं जातम्!"
            else
                flash[:alert] = "समूह चित्रं योजितुं न शक्यम्!"
            end
            redirect_to group_photos_path
        else
            redirect_to root_url
        end
    end

    def mgroup_photo_delete
        if session[:member]
            group_photo = GroupPhoto.find(params[:id])
            group_photo.destroy
            change = Change.new(time: Time.now, email: session[:email], table: "group_photos", cord: "delete")
            change.save
            flash[:notice] = "समूह चित्रं विलोपितं जातम्!"
            redirect_to group_photos_path
        else
            redirect_to root_url
        end
    end

    # Alumni CRUD operations

    def malumnicp
        if session[:member]
            alumni = Alumni.new(
                name: params[:name],
                branch: params[:branch],
                mail: params[:mail],
                linkedin: params[:linkedin]
            )
            
            if params[:image].present?
                uploaded_file = params[:image]
                file_name = "#{Time.now.to_i}_#{uploaded_file.original_filename}"
                file_path = Rails.root.join('public', 'uploads', 'alumni', file_name)
                
                FileUtils.mkdir_p(File.dirname(file_path))
                File.open(file_path, 'wb') do |file|
                    file.write(uploaded_file.read)
                end
                
                alumni.image = "/uploads/alumni/#{file_name}"
            end
            
            if alumni.save
                change = Change.new(time: Time.now, email: session[:email], table: "alumni", cord: "create")
                change.save
                flash[:notice] = 'पूर्वछात्रः सफलतया योजितः।'
                redirect_to all_teams_path  # Redirect to mteamr which shows both
            else
                flash[:alert] = 'त्रुटिः अभवत्।'
                redirect_to new_team_path  # Redirect to mteamc which has both forms
            end
        else
            redirect_to root_url
        end
    end

    def malumniu
        if session[:member]
            @alumni = Alumni.find(params[:id])
            render "malumniu"
        else
            redirect_to root_url
        end
    end

    def malumniup
        if session[:member]
            @alumni = Alumni.find(params[:id])
            
            @alumni.name = params[:alumni][:name] if params[:alumni][:name].present?
            @alumni.branch = params[:alumni][:branch] if params[:alumni][:branch].present?
            @alumni.mail = params[:alumni][:mail] if params[:alumni][:mail].present?
            @alumni.linkedin = params[:alumni][:linkedin] if params[:alumni][:linkedin].present?
            
            if params[:alumni][:image].present?
                # Delete old image
                old_image_path = Rails.root.join('public', @alumni.image) if @alumni.image
                File.delete(old_image_path) if old_image_path && File.exist?(old_image_path)
                
                # Upload new image
                uploaded_file = params[:alumni][:image]
                file_name = "#{Time.now.to_i}_#{uploaded_file.original_filename}"
                file_path = Rails.root.join('public', 'uploads', 'alumni', file_name)
                
                FileUtils.mkdir_p(File.dirname(file_path))
                File.open(file_path, 'wb') do |file|
                    file.write(uploaded_file.read)
                end
                
                @alumni.image = "/uploads/alumni/#{file_name}"
            end
            
            if @alumni.save
                change = Change.new(time: Time.now, email: session[:email], table: "alumni", cord: "update")
                change.save
                flash[:notice] = 'पूर्वछात्रः सफलतया अद्यतनीकृतः।'
                redirect_to all_alumni_path
            else
                flash[:alert] = 'त्रुटिः अभवत्।'
                redirect_to alumni_path(@alumni)
            end
        else
            redirect_to root_url
        end
    end

    def malumnidp
        if session[:member]
            @alumni = Alumni.find(params[:id])
            
            # Delete image file
            image_path = Rails.root.join('public', @alumni.image) if @alumni.image
            File.delete(image_path) if image_path && File.exist?(image_path)
            
            @alumni.destroy
            change = Change.new(time: Time.now, email: session[:email], table: "alumni", cord: "delete")
            change.save
            flash[:notice] = 'पूर्वछात्रः सफलतया नष्टः।'
            redirect_to all_alumni_path
        else
            redirect_to root_url
        end
    end
end

app/views/team/mgroup_photos.html.erb
<div class="admin-page">
  <div class="admin-header">
    <h1>समूह चित्राणि प्रबन्धनम्</h1>
    <p class="subtitle">Manage Group Photos</p>
  </div>

  <!-- Upload Form -->
  <div class="form-container" style="margin-bottom: 40px;">
    <div class="form-header">
      <span class="greeting">📸</span>
      <h2>नूतनं समूह चित्रं योजयतु</h2>
    </div>

    <%= form_with url: mgroup_photo_create_path, method: :post, local: true, multipart: true do |f| %>
      <div class="form-group">
        <label class="form-label">समूह चित्रं चिनोतु</label>
        <div class="file-input-wrapper">
          <%= f.file_field :image, accept: "image/*", required: true, class: "file-input", id: "group-photo-input" %>
          <label for="group-photo-input" class="file-input-label">
            <span class="upload-icon">📷</span>
            <span>चित्रं चिनोतु</span>
          </label>
        </div>
        <p class="form-hint">JPG, PNG वा JPEG स्वरूपे</p>
      </div>

      <div class="form-actions">
        <%= f.submit "चित्रं योजयतु", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <!-- Display existing photos -->
  <% if @group_photos.empty? %>
    <div class="empty-state">
      <i class="fa-solid fa-images" style="font-size: 64px; color: #ccc;"></i>
      <h2>कोऽपि समूह चित्रं नास्ति</h2>
      <p>कृपया प्रथमं चित्रं योजयतु</p>
    </div>
  <% else %>
    <div class="cards-grid">
      <% @group_photos.each do |photo| %>
        <div class="team-card">
          <div class="card-image">
            <% if photo.image.attached? %>
              <%= image_tag photo.image, class: "member-image" %>
            <% end %>
          </div>

          <div class="card-actions">
            <%= button_to delete_group_photo_path(photo), 
                method: :delete, 
                data: { confirm: "किं भवान् निश्चितः अस्ति?" },
                class: "btn btn-delete" do %>
              <i class="fa-solid fa-trash"></i>
              विलोपयतु
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/team/mteamc.html.erb
<div class="form-page">
  <div class="form-container">
    <!-- Team Member Form -->
    <div class="form-header">
      <div class="greeting">नमस्ते 🙏</div>
      <h1>नूतनं सदस्यं योजयतु</h1>
      <p class="form-subtitle">नवीनं सदस्यं सृजयतु</p>
    </div>

    <%= form_tag team_post_path, multipart: true, class: "modern-form" do %>
      <div class="form-group">
        <%= label_tag "नाम", nil, class: "form-label" %>
        <%= text_field_tag :name, nil, required: true, class: "form-input", placeholder: "सदस्यस्य नाम..." %>
      </div>

      <div class="form-group">
        <%= label_tag "वर्षं", nil, class: "form-label" %>
        <%= text_field_tag :year, nil, required: true, class: "form-input", placeholder: "वर्षं (उदा. २०२४)..." %>
      </div>

      <div class="form-group">
        <%= label_tag "शाखा", nil, class: "form-label" %>
        <%= text_field_tag :branch, nil, required: true, class: "form-input", placeholder: "शाखा (उदा. CSE, ECE)..." %>
      </div>

      <div class="form-group">
        <%= label_tag "विद्युत्पत्रम्", nil, class: "form-label" %>
        <%= email_field_tag :mail, nil, required: true, class: "form-input", placeholder: "विद्युत्पत्रं..." %>
      </div>

      <div class="form-group">
        <%= label_tag "चित्रम्", nil, class: "form-label" %>
        <div class="file-input-wrapper">
          <%= file_field_tag :image, required: true, class: "file-input", id: "team-image-input", accept: "image/*" %>
          <label for="team-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span id="team-file-name">चित्रं चिनोतु</span>
          </label>
        </div>
        <div id="team-preview" class="file-preview" style="display: none;">
          <span class="preview-icon">✓</span>
          <span class="preview-text"></span>
        </div>
      </div>

      <div class="form-actions">
        <%= submit_tag "अग्रेस्थापनं करोतु", class: "btn btn-primary" %>
        <%= link_to "प्रतिगच्छतु", all_teams_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>

  <!-- Divider -->
  <div class="form-divider">
    <span class="divider-text">अथवा</span>
  </div>

  <!-- Alumni Form -->
  <div class="form-container alumni-form">
    <div class="form-header">
      <div class="greeting">🎓</div>
      <h1>पूर्वछात्रं योजयतु</h1>
      <p class="form-subtitle">नवीनं पूर्वछात्रं सृजयतु</p>
    </div>

    <%= form_tag alumni_post_path, multipart: true, class: "modern-form" do %>
      <div class="form-group">
        <%= label_tag "नाम", nil, class: "form-label" %>
        <%= text_field_tag :name, nil, required: true, class: "form-input", placeholder: "पूर्वछात्रस्य नाम..." %>
      </div>

      <div class="form-group">
        <%= label_tag "शाखा", nil, class: "form-label" %>
        <%= text_field_tag :branch, nil, required: true, class: "form-input", placeholder: "शाखा (उदा. CSE, ECE)..." %>
      </div>

      <div class="form-group">
        <%= label_tag "विद्युत्पत्रम्", nil, class: "form-label" %>
        <%= email_field_tag :mail, nil, required: true, class: "form-input", placeholder: "विद्युत्पत्रं..." %>
      </div>

      <div class="form-group">
        <%= label_tag "LinkedIn", nil, class: "form-label" %>
        <%= url_field_tag :linkedin, nil, required: true, class: "form-input", placeholder: "LinkedIn संयोजनम्..." %>
      </div>

      <div class="form-group">
        <%= label_tag "चित्रम्", nil, class: "form-label" %>
        <div class="file-input-wrapper">
          <%= file_field_tag :image, required: true, class: "file-input", id: "alumni-image-input", accept: "image/*" %>
          <label for="alumni-image-input" class="file-input-label">
            <i class="upload-icon">📁</i>
            <span id="alumni-file-name">चित्रं चिनोतु</span>
          </label>
        </div>
        <div id="alumni-preview" class="file-preview" style="display: none;">
          <span class="preview-icon">✓</span>
          <span class="preview-text"></span>
        </div>
      </div>

      <div class="form-actions">
        <%= submit_tag "अग्रेस्थापनं करोतु", class: "btn btn-primary alumni-btn" %>
        <%= link_to "प्रतिगच्छतु", all_teams_path, class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>


<script>
document.addEventListener('DOMContentLoaded', function() {
  // Team image upload
  const teamFileInput = document.getElementById('team-image-input');
  const teamFileName = document.getElementById('team-file-name');
  const teamPreview = document.getElementById('team-preview');
  const teamPreviewText = teamPreview.querySelector('.preview-text');
  
  teamFileInput.addEventListener('change', function() {
    if (this.files && this.files.length > 0) {
      const file = this.files[0];
      teamFileName.textContent = file.name;
      teamPreviewText.textContent = `चयनितं: ${file.name} (${(file.size / 1024 / 1024).toFixed(2)} MB)`;
      teamPreview.style.display = 'flex';
    } else {
      teamFileName.textContent = 'चित्रं चिनोतु';
      teamPreview.style.display = 'none';
    }
  });

  // Alumni image upload
  const alumniFileInput = document.getElementById('alumni-image-input');
  const alumniFileName = document.getElementById('alumni-file-name');
  const alumniPreview = document.getElementById('alumni-preview');
  const alumniPreviewText = alumniPreview.querySelector('.preview-text');
  
  alumniFileInput.addEventListener('change', function() {
    if (this.files && this.files.length > 0) {
      const file = this.files[0];
      alumniFileName.textContent = file.name;
      alumniPreviewText.textContent = `चयनितं: ${file.name} (${(file.size / 1024 / 1024).toFixed(2)} MB)`;
      alumniPreview.style.display = 'flex';
    } else {
      alumniFileName.textContent = 'चित्रं चिनोतु';
      alumniPreview.style.display = 'none';
    }
  });
});
</script>

app/views/team/mteamr.html.erb
<div class="admin-page">
  <div class="admin-header">
    <h1>सदस्याः प्रबन्धनम्</h1>
    <p class="subtitle">सर्वे सदस्याः अत्र दृश्यन्ते</p>
    <div class="admin-actions">
      <%= link_to new_team_path, class: "btn btn-primary" do %>
        <i class="fa-solid fa-user-plus"></i>
        <span>नूतनं सदस्यं योजयतु</span>
      <% end %>
      <%= link_to group_photos_path, class: "btn btn-secondary", style: "color:#54101d" do %>
        <i class="fa-solid fa-images"></i>
        <span>समूह चित्राणि</span>
      <% end %>
    </div>
  </div>

  <% if @teams.empty? %>
    <div class="empty-state">
      <i class="fa-solid fa-users" style="font-size: 64px; color: #ccc;"></i>
      <h2>कोऽपि सदस्यः नास्ति</h2>
      <p>प्रथमं सदस्यं योजयतु</p>
      <%= link_to "सदस्यं योजयतु", new_team_path, class: "btn btn-primary" %>
    </div>
  <% else %>
    <div class="cards-grid">
      <% @teams.each do |team| %>
        <div class="team-card">
          <div class="card-image">
            <% if team.image.attached? %>
              <%= image_tag team.image, alt: team.name, class: "member-image" %>
            <% else %>
              <div class="no-image">
                <i class="fa-solid fa-user"></i>
              </div>
            <% end %>
          </div>
          
          <div class="card-content">
            <h3 class="member-name"><%= team.name %></h3>
            
            <div class="member-info">
              <div class="info-item">
                <i class="fa-solid fa-calendar"></i>
                <span><%= team.year %></span>
              </div>
              
              <div class="info-item">
                <i class="fa-solid fa-graduation-cap"></i>
                <span><%= team.branch %></span>
              </div>
              
              <div class="info-item">
                <i class="fa-solid fa-envelope"></i>
                <span><%= team.mail %></span>
              </div>
            </div>
          </div>
          
          <div class="card-actions">
            <%= link_to team_path(team.id), class: "btn btn-edit" do %>
              <i class="fa-solid fa-pen"></i>
               परिवर्तयतु
            <% end %>
            <%= button_to team_delete_path(team.id), method: :delete, data: { confirm: "किं भवान् निश्चितः अस्ति?" }, class: "btn btn-delete" do %>
              <i class="fa-solid fa-trash"></i> विनश्यतु
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Alumni Section Divider -->
  <div class="section-divider">
    <h2>पूर्वछात्राः प्रबन्धनम्</h2>
    <p class="section-subtitle">Alumni Management</p>
  </div>

  <!-- Alumni Header with Add Button -->
  <div class="admin-header alumni-section-header">
    <div class="admin-actions">
      <%= link_to new_team_path, class: "btn btn-primary alumni-btn" do %>
        <i class="fa-solid fa-user-graduate"></i>
        <span>नूतनं पूर्वछात्रं योजयतु</span>
      <% end %>
    </div>
  </div>

  <!-- Alumni Section -->
  <% if @alumnis.empty? %>
    <div class="empty-state">
      <i class="fa-solid fa-user-graduate" style="font-size: 64px; color: #ccc;"></i>
      <h2>कोऽपि पूर्वछात्रः नास्ति</h2>
      <p>पूर्वछात्राः mteamc पृष्ठे योजिताः भविष्यन्ति</p>
    </div>
  <% else %>
    <div class="cards-grid">
      <% @alumnis.each do |alumni| %>
        <div class="team-card alumni-card">
          <div class="card-image">
            <% if alumni.image.present? %>
              <%= image_tag alumni.image, alt: alumni.name, class: "member-image" %>
            <% else %>
              <div class="no-image alumni-no-image">
                <i class="fa-solid fa-user-graduate"></i>
              </div>
            <% end %>
          </div>
          
          <div class="card-content">
            <h3 class="member-name"><%= alumni.name %></h3>
            
            <div class="member-info">
              <div class="info-item">
                <i class="fa-solid fa-graduation-cap"></i>
                <span><%= alumni.branch %></span>
              </div>
              
              <div class="info-item">
                <i class="fa-solid fa-envelope"></i>
                <span><%= alumni.mail %></span>
              </div>
              
              <% if alumni.linkedin.present? %>
                <div class="info-item">
                  <i class="fa-brands fa-linkedin"></i>
                  <a href="<%= alumni.linkedin %>" target="_blank" style="color: #47596f; text-decoration: none;">Profile</a>
                </div>
              <% end %>
            </div>
          </div>
          
          <div class="card-actions">
            <%= link_to alumni_path(alumni.id), class: "btn btn-edit" do %>
              <i class="fa-solid fa-pen"></i>
               परिवर्तयतु
            <% end %>
            <%= button_to alumni_delete_path(alumni.id), method: :delete, data: { confirm: "किं भवान् निश्चितः अस्ति?" }, class: "btn btn-delete" do %>
              <i class="fa-solid fa-trash"></i> विनश्यतु
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/team/profile.html.erb
<div class="button">
    <%= link_to "Back", member_area_path, class: "anone" %>
</div>

    <%= content_tag :div, class: "teams" do %>
        <div class="title">
            <%= @team.name %><br/>
        </div>
        <div class="title">
            <%= @team.email %><br/>
        </div>
    <% end %>